# ASP.NET Core
trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk 3.x'
    inputs:
      packageType: 'sdk'
      version: '3.x'

  - script: |
      echo "Accessing the application link: qa.divaaco.com"
      echo "Running manual test case with Test Plan ID: 7771, Test Suite ID: 7774, Test Case ID: 7813..."

  - task: PublishTestResults@2
    displayName: 'Publish Test Results'
    inputs:
      testResultsFiles: 'Progress report'
      searchFolder: '$(System.DefaultWorkingDirectory)'
      testRunTitle: 'Automated Test Results'
     